---
# Update Apt Repository

- name: Commmon | Update repository
  apt: update_cache=yes

# Python Requirements

- name: Commmon | python-software-properties
  apt: pkg=python-software-properties state=installed

# ACL - for easy access control management

- name: Common | ACL
  apt: pkg=acl state=installed

# cURL

- name: Common | cURL
  apt: pkg=curl state=installed

# Git

- name: Common | Install Git
  apt: pkg=git-core state=installed

# Host Configuration

- name: Common | Set the hostname /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: Copy the hosts file into place
  template: src=../files/hosts dest=/etc/hosts mode=0600
